name: Metrics

on:
  # Schedule daily updates
  schedule:
    - cron: "0 0 * * *"
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push:
    branches: ["master", "main"]

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Debug to check if token is set
      - name: Debug token
        run: |
          if [ -z "${{ secrets.TOKEN }}" ]; then
            echo "❌ Token is missing! Did you add it in Settings > Secrets and variables > Actions?"
            exit 1
          else
            echo "✅ Token is present (value hidden)."
          fi

      # Step 2: Generate metrics
      - name: Generate GitHub metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.TOKEN }}
